/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import DataBase.CConexion;
import Modelo.CmPruebas;

/**
 *
 * @author
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

    private CmPruebas pruebas;
    private static int idPruebas;
    private static int idHojaPruebas;
    public  static int cupos;
    

    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal() {      
        initComponents();
        System.out.println(" entro al formulario principal");
         lblinfFupas.setText("NRO. DE FUPAS DISPONIBLES: "+frmMenuPrincipal.cupos);  
    }

    public static int getIdPruebas() {
        return idPruebas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblinfFupas = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnLuces = new javax.swing.JButton();
        btnFrenos = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnRuido = new javax.swing.JButton();
        btnGases1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 158, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU PRINCIPAL");

        lblinfFupas.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblinfFupas.setText("NRO. DE FUPAS DISPONIBLES:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblinfFupas, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblinfFupas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fin.png"))); // NOI18N
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnLuces.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/foco.png"))); // NOI18N
        btnLuces.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLucesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLucesMouseExited(evt);
            }
        });
        btnLuces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLucesActionPerformed(evt);
            }
        });

        btnFrenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/rueda.png"))); // NOI18N
        btnFrenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFrenosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFrenosMouseExited(evt);
            }
        });
        btnFrenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrenosActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnRuido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bocina.png"))); // NOI18N
        btnRuido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRuidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRuidoMouseExited(evt);
            }
        });
        btnRuido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRuidoActionPerformed(evt);
            }
        });

        btnGases1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/emisiones.png"))); // NOI18N
        btnGases1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGases1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGases1MouseExited(evt);
            }
        });
        btnGases1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGases1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnGases1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLuces)
                        .addGap(18, 18, 18)
                        .addComponent(btnFrenos)
                        .addGap(18, 18, 18)
                        .addComponent(btnRuido)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFrenos)
                    .addComponent(btnLuces)
                    .addComponent(btnRuido)
                    .addComponent(btnGases1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        CConexion.execStoredProcRestoredFechaFinal();
        this.setVisible(false);
        frmLogin login = new frmLogin();
        
        login.setVisible(true);
        login.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cargarIdPrueba(int idTipoPrueba) {
        pruebas = new CmPruebas();
        if (pruebas.buscarPrueba(idHojaPruebas, idTipoPrueba)) {
            idPruebas = pruebas.getIdPruebas();
        }
    }

    private void btnLucesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLucesActionPerformed
        lblinfFupas.setText("NRO. DE FUPAS DISPONIBLES: "+frmMenuPrincipal.cupos);  
        this.setVisible(false);
        cargarIdPrueba(2);
        frmLuces luces = new frmLuces();
        luces.setExtendedState(MAXIMIZED_BOTH);
        luces.setVisible(true);
    }//GEN-LAST:event_btnLucesActionPerformed

    private void btnFrenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrenosActionPerformed
        this.setVisible(false);
        cargarIdPrueba(5);
        frmFrenos frenos = new frmFrenos();
        frenos.setExtendedState(MAXIMIZED_BOTH);
        frenos.setVisible(true);
    }//GEN-LAST:event_btnFrenosActionPerformed

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/finCambio.png")));
        lblTitulo.setText("SALIR");
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/finCambio.png")));
        lblTitulo.setText("SALIR");
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnLucesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLucesMouseEntered
        btnLuces.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/focoCambio.png")));
        lblTitulo.setText("LUCES");
    }//GEN-LAST:event_btnLucesMouseEntered

    private void btnLucesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLucesMouseExited
        btnLuces.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/foco.png")));
        lblTitulo.setText(null);
    }//GEN-LAST:event_btnLucesMouseExited

    private void btnFrenosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFrenosMouseEntered
        btnFrenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ruedaCambio.png")));
        lblTitulo.setText("FRENOS");
    }//GEN-LAST:event_btnFrenosMouseEntered

    private void btnFrenosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFrenosMouseExited
        btnFrenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/rueda.png")));
        lblTitulo.setText(null);
    }//GEN-LAST:event_btnFrenosMouseExited

    private void btnRuidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRuidoMouseEntered
        btnRuido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bocinaCambio.png")));
        lblTitulo.setText("RUIDO");
    }//GEN-LAST:event_btnRuidoMouseEntered

    private void btnRuidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRuidoMouseExited
        btnRuido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bocina.png")));
        lblTitulo.setText(null);
    }//GEN-LAST:event_btnRuidoMouseExited

    private void btnRuidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRuidoActionPerformed
        this.setVisible(false);
        cargarIdPrueba(7);
        frmRuido ruido = new frmRuido();
        ruido.setExtendedState(MAXIMIZED_BOTH);
        ruido.setVisible(true);
    }//GEN-LAST:event_btnRuidoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        CConexion.execStoredProcChangeFechaFinal();
        pruebas = new CmPruebas();
        idHojaPruebas = frmLogin.getIdHojaPruebas();
        System.out.println("Id Hoja Prueba: " + idHojaPruebas);
        if (!pruebas.buscarPrueba(idHojaPruebas, 5)) {
            btnFrenos.setEnabled(false);
        }
        if (!pruebas.buscarPrueba(idHojaPruebas, 2)) {
            btnLuces.setEnabled(false);
        }
        if (!pruebas.buscarPrueba(idHojaPruebas, 8)) {
            btnGases1.setEnabled(false);
        }
        if (!pruebas.buscarPrueba(idHojaPruebas, 7)) {
            btnRuido.setEnabled(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnGases1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGases1MouseEntered
        btnGases1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/emisionesCambio.png")));
        lblTitulo.setText("GASES");
    }//GEN-LAST:event_btnGases1MouseEntered

    private void btnGases1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGases1MouseExited
      this.btnGases1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/emisiones.png")));
        lblTitulo.setText(null);
    }//GEN-LAST:event_btnGases1MouseExited

    private void btnGases1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGases1ActionPerformed
          lblinfFupas.setText("NRO. DE FUPAS DISPONIBLES: "+frmMenuPrincipal.cupos);  
        this.setVisible(false);
        cargarIdPrueba(8);
        frmGases gases  = new frmGases();      
        gases.setExtendedState(MAXIMIZED_BOTH);
        gases.setVisible(true);
    }//GEN-LAST:event_btnGases1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       CConexion.execStoredProcRestoredFechaFinal();
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFrenos;
    private javax.swing.JButton btnGases1;
    private javax.swing.JButton btnLuces;
    private javax.swing.JButton btnRuido;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblinfFupas;
    // End of variables declaration//GEN-END:variables
}
